_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 800000

model:
  type: UPerNet
  backbone:
    type: SwinTransformer_small_residual_PP
    num_classes: 4
    in_channels: 4
    pretrained: Null #./output_upernet_CRSwin_small/model.pdparams #../../bigpaper/upernet_CRSwin_smal/iter_70000/model.pdparams #output_upernet_CSwin_small/best_model/model.pdparams
  backbone_indices: [0, 1, 2, 3, 4]
  channels: 32
  dropout_prob: 0.3
  enable_auxiliary_loss: False

optimizer:
  type: AdamW
  weight_decay: 0.01



loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.3, 0.7]
  coef: [1]


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  end_lr: 0
  power: 1.0