_base_: '../_base_/brats2020.yml'

batch_size: 2
iters: 800000

model:
  type: UPerNet
  backbone:
    type: SwinTransformer
    in_channels: 4
    embed_dim: 64
    depths: [2, 2, 6, 2]
    num_heads: [4, 8, 16, 32]
  backbone_indices: [0, 1, 2, 3]
  channels: 256
  dropout_prob: 0.3
  enable_auxiliary_loss: False

optimizer:
  type: AdamW
  weight_decay: 0.01



loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.3, 0.7]
  coef: [1]


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  end_lr: 0
  power: 1.0