_base_: '../_base_/brats2020Adwm1_missloss.yml'

batch_size: 8
iters: 800000

model:
  type: UPerNet
  backbone:
    type: CSwin_Unet_uper
    in_channels: 4
    num_classes: 4
    pretrained: Null #./output_swin_transformer_unet1_small_residual/iter_200000/model.pdparams
  num_classes: 4
  backbone_indices: [0, 1, 2, 3]
  channels: 32
  dropout_prob: 0.3
  enable_auxiliary_loss: False
